contas/urls.py
from django.urls import path

from .views import MeuPerfilView, EditarContaView, AtualizarSenhaContaView, MeusPostsView


app_name = "perfil"

urlpatterns = [
    path('',MeuPerfilView.as_view(), name='meu_perfil'),
    path('editar/', EditarContaView, name='editar_perfil'),
    path('editar_senha/', AtualizarSenhaContaView.as_view(), name="editar_senha"),
    path('posts/', MeusPostsView.as_view(), name='minhas_postagens'),
]

postagens/urls.py
from django.urls import path

from .views import (
    ListarPosts,
    VerDetalhesPosts,
    ListarPostsPorCategoria,
    CriarPost,
    AtualizarPost,
    DeletarPost,
    ListarCategorias,
    VerDetalhesCategorias,
    CriarCategoria,
    AtualizarCategoria,
    DeletarCategoria
)

app_name = "blog"

urlpatterns = [
    path('', ListarPosts.as_view(), name="listar_posts"),
    path('<int:pk>/', VerDetalhesPosts.as_view(), name='detalhe_post'),
    path('por_categoria/<titulo>/', ListarPostsPorCategoria.as_view(), name='listar_posts_por_categoria'),
    path('criar/', CriarPost.as_view(), name="criar_post"),
    path('<int:pk>/atualizar/', AtualizarPost.as_view(), name='atualizar_post'),
    path('<int:pk>/deletar/', DeletarPost.as_view(), name='deletar_post'),
    path('categorias/', ListarCategorias.as_view(), name="listar_categorias"),
    path('categorias/<int:pk>/', VerDetalhesCategorias.as_view(), name='detalhe_categoria'),
    path('categorias/criar/', CriarCategoria.as_view(), name="criar_categoria"),
    path('categorias/<int:pk>/atualizar/', AtualizarCategoria.as_view(), name='atualizar_categoria'),
    path('categorias/<int:pk>/deletar/', DeletarCategoria.as_view(), name='deletar_categoria'),
]

techblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler400, handler403,handler404, handler500)
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from contas.views import HomepageView, CriarContaView,AjudaView
from contas.forms import MeuLoginForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomepageView.as_view(), name='homepage'),
    path('ajuda/', AjudaView.as_view(), name="ajuda"),
    path('blog/', include('postagens.urls', namespace='blog')),
    path('perfil/', include('contas.urls', namespace='perfil')),
    path('login/', LoginView.as_view(authentication_form=MeuLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', CriarContaView.as_view(), name='registro'),
    path('djrichtextfield/', include('djrichtextfield.urls'))
]

handler404 = "contas.views.pagina_nao_encontrada_view"
handler400 = "contas.views.pagina_requisicao_negadada"
handler403 = "contas.views.pagina_permissao_negada_view"
handler500 = "contas.views.pagina_error_view"
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postagens/models.py
from django.db import models
from contas.models import Usuario

from PIL import Image
from djrichtextfield.models import RichTextField

class Postagem(models.Model):
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="postagens/", default="postagens/predefinido/default.png")
    titulo = models.CharField(max_length=100)
    texto = RichTextField()
    data_adicao = models.DateField(auto_now_add=True)
    categorias = models.ManyToManyField("Categoria", blank=True)

    class Meta:
        verbose_name = "postagem"
        verbose_name_plural = "postagens"
        ordering = ["-data_adicao"]

    def save(self, *args, **kwargs):
        super().save() # salva a imagem primeiro

        img = Image.open(self.foto.path) # Abrindo imagem usando SELF

        if img.height > 400 or img.width > 800:
            nova_foto = (1200,800)
            img.thumbnail(nova_foto)
            img.save(self.foto.path) # Salva nova imagem no mesmo local

    def __str__(self):
        return self.titulo
    

class Categoria(models.Model):
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.titulo

postagens/forms.py
from django import forms

from .models import Postagem, Categoria

class PostagemModelForm(forms.ModelForm):
    class Meta:
        model = Postagem
        fields = (
            'foto',
            'titulo',
            'texto',
            'categorias',
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['foto'].widget.attrs.update({'class':'w-full '})
        self.fields['titulo'].widget.attrs.update({'class':'w-full '})
        # self.fields['texto'].widget.attrs.update({'class':'text-red-600'})
        self.fields['categorias'].widget.attrs.update({'class':'w-full'})

class CategoriaModelForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = (
            'titulo',
            'descricao',
        )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['titulo'].widget.attrs.update({'class':'w-full border-2 bg-white/40  text-xl m-2 rounded-xl pl-1'})
        self.fields['descricao'].widget.attrs.update({'class':'w-full border-2 bg-white/40  text-xl m-2 rounded-xl pl-1'})

postagens/views.py
from django.shortcuts import render, redirect, reverse,HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views import generic
from django.db.models import Q

from .models import Postagem, Categoria
from .forms import PostagemModelForm, CategoriaModelForm

from contas.models import Usuario
from contas.mixins import AdminAndLoginRequired,AdminOrOwnerRequired

class ListarPosts(generic.ListView):
    template_name = "postagens/listar_postagens.html"
    context_object_name = "postagens"
    model = Postagem
    paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('q')
        if(query == None):
            queryset = Postagem.objects.all()
            return queryset
        else:
            queryset = Postagem.objects.filter(Q(titulo__icontains = query))
            return queryset

class VerDetalhesPosts(generic.DetailView):
    template_name = "postagens/detalhes_postagem.html"
    context_object_name= "postagem"
    model = Postagem

class ListarPostsPorCategoria(generic.ListView):
    template_name = "postagens/listar_postagens.html"
    context_object_name = "postagens"
    model = Postagem

    def get_context_data(self,**kwargs):
        data = super().get_context_data(**kwargs)
        data['mensagem'] =f"sobre {self.kwargs['titulo']}"
        return data

    def get_queryset(self):
        categoria_titulo = self.kwargs['titulo']
        postagens = Postagem.objects.filter(categorias__titulo = categoria_titulo)
        return postagens


class CriarPost(LoginRequiredMixin, generic.CreateView):
    template_name = "postagens/form_postagem.html"
    form_class = PostagemModelForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['acao'] = "Criar nova postagem"
        data['botao'] = "Criar"
        return data
    
    def form_valid(self, form):
        perfil = Usuario.objects.get(pk = self.request.user.pk)
        categorias = form.cleaned_data['categorias']
        obj = form.save(commit=False)
        obj.autor = perfil
        obj.save()
        lista_categorias = Categoria.objects.filter(pk__in = categorias)
        for ct in lista_categorias:
            obj.categorias.add(ct)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("blog:listar_posts")
    

class AtualizarPost(AdminOrOwnerRequired, generic.UpdateView):
    template_name = "postagens/form_postagem.html"
    context_object_name = "postagem"
    form_class = PostagemModelForm
    model = Postagem
    queryset = Postagem.objects.all()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['acao'] = "Atualizar Postagem"
        data['botao'] = "Atualizar"
        return data
    
    def get_success_url(self):
        return reverse("blog:listar_posts")

class DeletarPost(LoginRequiredMixin, generic.DeleteView):
    template_name = "postagens/deletar_postagem.html"
    model = Postagem
    queryset = Postagem.objects.all()

    def get_object(self, queryset=None):
        """Verifica se é um admin ou se é o autor do post."""
        obj = super(DeletarPost, self).get_object()
        if self.request.user.admin:
            return obj
        else:
            if not obj.autor.pk == self.request.user.pk:
                raise PermissionDenied()
            else:
                return obj
    def get_success_url(self):
        return reverse("blog:listar_posts")
    
class ListarCategorias(generic.ListView):
    template_name = "categorias/listar_categorias.html"
    context_object_name = "categorias"
    model = Categoria

class VerDetalhesCategorias(generic.DetailView):
    template_name = "categorias/detalhes_categoria.html"
    context_object_name = "categoria"
    model = Categoria

class CriarCategoria(AdminAndLoginRequired, generic.CreateView):
    template_name = "categorias/form_categoria.html"
    form_class = CategoriaModelForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['acao'] = "Criar nova categoria"
        data['botao'] = "Criar"
        return data

    def get_success_url(self):
        return reverse("blog:listar_categorias")

class AtualizarCategoria(AdminAndLoginRequired, generic.UpdateView):
    template_name = "categorias/form_categoria.html"
    context_object_name = "categoria"
    form_class = CategoriaModelForm
    model = Categoria
    queryset = Categoria.objects.all()

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['acao'] = "Atualizar categoria"
        data['botao'] = "Atualizar"
        return data

    def get_success_url(self):
        return reverse("blog:listar_categorias")

class DeletarCategoria(AdminAndLoginRequired, generic.DeleteView):
    template_name = "categorias/deletar_categoria.html"
    model = Categoria
    queryset = Categoria.objects.all()

    def get_success_url(self):
        return reverse("blog:listar_categorias")

postagens/templates/postagens/deletar_postagem.html
{% extends "base.html" %} {% block content %}
<div class="h-screen xl:w-1/2 md:w-2/3 mx-auto mt-20">
  <form
    method="POST"
    class="bg-gray-700/60 backdrop-blur-sm rounded-xl border border-white p-2"
  >
    <h1
      class="text-3xl font-semibold uppercase underline text-center m-2 text-white"
    >
      Voce tem certeza de que gostaria de deletar está postagem?
    </h1>
    {% csrf_token %}
    <div class="p-2 text-white text-2xl font-semibold">{{form.as_p}}</div>
    <div class="mt-2 flex gap-2 justify-center text-center">
      <button
        class="p-2 w-24 text-xl bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 rounded-xl transition ease-in-out duration-700"
      >
        Deletar
      </button>
      <a
        href="{% url 'blog:listar_posts' %}"
        class="p-2 w-24 text-xl bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 rounded-xl transition ease-in-out duration-700"
        >Cancelar</a
      >
    </div>
  </form>
</div>
{% endblock content %}

postagens/templates/postagens/detalhes_postagem.html
{% extends "base.html" %} {% block content %}
<div
  class="bg-gray-700/60 backdrop-blur-sm text-white mx-auto p-2 mt-20 mb-4 rounded-xl border border-white"
  style="width: 800px"
>
  <div class="flex flex-col gap-2">
    <img
      src="{{postagem.foto.url}}"
      alt="Foto do Post"
      class="rounded-xl foto_postagem"
    />
    {% comment %} Infos {% endcomment %}
    <div class="flex flex-col gap-2 ml-2">
      {% comment %} Info Autor e Data {% endcomment %}
      <div class="flex gap-2 items-center">
        <img
          src="{{postagem.autor.foto.url}}"
          alt="foto do autor"
          class="rounded-full w-20"
        />
        <div class="flex flex-col">
          <span>{{postagem.autor.username}}</span>
          <span class="text-sm"
            >Postagem de {{postagem.data_adicao | date:'d/m/y'}}</span
          >
        </div>
      </div>
      {% comment %} Categorias {% endcomment %}
    </div>
    <h1 class="ml-4 text-4xl font-bold">{{postagem.titulo}}</h1>
    <div class="flex gap-2 ml-4">
      {% for cts in postagem.categorias.all %}
      <a
        href="{% url 'blog:detalhe_categoria' cts.pk %}"
        class="bg-red-300 hover:bg-red-600 text-gray-600 hover:text-gray-200 font-semibold px-1 rounded transition ease-in-out duration-700"
        >{{cts.titulo}}</a
      >
      {% endfor %}
    </div>
    <div class="text-xl ml-4">
      <p>{{postagem.texto|safe}}</p>
      {% comment %} Validacao Visual para Editar e Apagar {% endcomment %}
      <div class="flex gap-2 justify-center mt-2">
        {% if request.user.id == postagem.autor.id %}
        <a
          href="{%  url 'blog:atualizar_post' postagem.pk %}"
          class="bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 font-semibold rounded-xl text-2xl px-2 py-1 transition ease-in-out duration-700"
          >Editar</a
        >
        <a
          href="{%  url 'blog:deletar_post' postagem.pk %}"
          class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 font-semibold rounded-xl text-2xl px-2 py-1 transition ease-in-out duration-700"
          >Deletar</a
        >
        {% else %} {% if request.user.admin %}
        <a
          href="{%  url 'blog:atualizar_post' postagem.pk %}"
          class="bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 font-semibold rounded-xl text-2xl px-2 py-1 transition ease-in-out duration-700"
          >Editar</a
        >
        <a
          href="{%  url 'blog:deletar_post' postagem.pk %}"
          class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 font-semibold rounded-xl text-2xl px-2 py-1 transition ease-in-out duration-700"
          >Deletar</a
        >
        {% else %} {% endif %} {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

postagens/templates/postagens/form_postagem.html
{% extends "base.html" %} {% block content %}
<div class="xl:w-1/2 md:w-2/3 mx-auto mb-4 mt-20">
  <form
    method="POST"
    class="bg-gray-700/60 backdrop-blur-sm rounded-xl border border-white p-2"
    enctype="multipart/form-data"
  >
    <h1
      class="text-3xl font-semibold uppercase underline text-center m-2 text-white"
    >
      {{acao}}
    </h1>
    {% csrf_token %}
    <div class="p-2 text-gray-500 text-2xl font-semibold">{{form.as_p}}</div>
    <div class="mt-2 flex gap-2 justify-center text-center">
      <button
        class="p-2 w-24 text-xl bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 rounded-xl transition ease-in-out duration-700"
      >
        {{botao}}
      </button>
      <a
        href="{% url 'blog:listar_posts' %}"
        class="p-2 w-24 text-xl bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 rounded-xl transition ease-in-out duration-700"
        >Cancelar</a
      >
    </div>
  </form>
</div>
{% endblock content %}

postagens/templates/postagens/listar_postagens.html
{% extends "base.html" %} {% block content %}
<div class="mt-6 w-2/3 mx-auto mb-2">
{% if request.user.is_authenticated %}
<a href="{% url 'blog:criar_post' %}" class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 text-3xl font-bold px-4 rounded-xl ml-2 transition ease-in-out duration-700">Novo Post</a>
{% else %}
{% endif %}
<form action="{% url 'blog:listar_posts' %}" method="GET" class="flex mt-4 pl-2 text-black text-xl">
        <input name="q" type="text" placeholder="Pesquise Pelo Post" class="w-96 rounded-l-xl py-1 pl-1">
        <button type="submit" class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 rounded-r-xl py-1 px-2">Pesquisar</button>
    </form>
</div>
<div class="bg-gray-700/60 backdrop-blur-sm text-white w-2/3 mx-auto rounded-xl p-2 mt-4">
  <h1 class="text-5xl text-center font-bold uppercase underline">Postagens {{mensagem}}</h1>
  <div class="flex flex-col gap-1 mt-2">
    {% for post in postagens %}
    <div class="py-8 px-4  bg-black/30 border-2 border-white rounded-xl">
      <div class="h-full flex items-start">
        <div class="w-12 flex-shrink-0 flex flex-col text-center leading-none">
          <span class="text-white pb-2 mb-2 border-b-2 border-gray-200"
            >{{post.data_adicao | date:'M'}}</span
          >
          <span
            class="font-medium text-lg text-white title-font leading-none"
            >{{post.data_adicao | date:'d'}}</span
          >
        </div>
        <div class="flex-grow pl-6">
          <h2
            class="tracking-widest text-xs title-font font-medium text-red-600 mb-1"
          >
            TÍTULO
          </h2>
          <h1 class="title-font text-xl font-medium text-white mb-3">
            {{post.titulo}}
          </h1>
          <p class="leading-relaxed text-gray-200 mb-5">
            {{post.texto |truncatechars_html:200 | safe}}...
          </p>
          <div class="mb-2 ">
            <a class="text-red-400 hover:text-red-600 font-semibold px-2 py-1 rounded-md " href="{% url 'blog:detalhe_post' post.pk %}">Ler Mais</a>
          </div>
          <div class="mb-2 border border-white"></div>
          <a class="inline-flex items-center">
          <span class="text-2xl font-bold bg-red-600 text-white px-3 py-1 rounded-full ">A</span>
            <span class="flex-grow flex flex-col pl-2">
              <span class="title-font font-medium text-white"
                >{{post.autor}}</span
              >
            </span>
          </a>
        </div>
      </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% if is_paginated %}
<div class="text-white text-xl font-semibold flex gap-2 justify-center bg-gray-700/60 backdrop-blur-sm mt-2 p-2 w-2/3  mb-4 mx-auto rounded-xl items-center">
{% if page_obj.has_previous %}
<div><a href="?page={{ page_obj.previous_page_number }}" class="text-white hover:text-gray-200 font-bold text-3xl">&#9668;</a></div>
{% else %}
{% endif %}
  <div><span>{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span></div>
{% if page_obj.has_next %}
<div><a href="?page={{ page_obj.next_page_number }}" class="text-white hover:text-gray-200 font-bold text-3xl">&#9658;
</a></div>
{% else %}
{% endif %}
</div>
{% else %}
{% endif %}
{% endblock content %}
</div>