contas/urls.py
from django.urls import path

from .views import MeuPerfilView, EditarContaView, AtualizarSenhaContaView, MeusPostsView


app_name = "perfil"

urlpatterns = [
    path('',MeuPerfilView.as_view(), name='meu_perfil'),
    path('editar/', EditarContaView, name='editar_perfil'),
    path('editar_senha/', AtualizarSenhaContaView.as_view(), name="editar_senha"),
    path('posts/', MeusPostsView.as_view(), name='minhas_postagens'),
]

postagens/urls.py
from django.urls import path

from .views import (
    ListarPosts,
    VerDetalhesPosts,
    ListarPostsPorCategoria,
    CriarPost,
    AtualizarPost,
    DeletarPost,
    ListarCategorias,
    VerDetalhesCategorias,
    CriarCategoria,
    AtualizarCategoria,
    DeletarCategoria
)

app_name = "blog"

urlpatterns = [
    path('', ListarPosts.as_view(), name="listar_posts"),
    path('<int:pk>/', VerDetalhesPosts.as_view(), name='detalhe_post'),
    path('por_categoria/<titulo>/', ListarPostsPorCategoria.as_view(), name='listar_posts_por_categoria'),
    path('criar/', CriarPost.as_view(), name="criar_post"),
    path('<int:pk>/atualizar/', AtualizarPost.as_view(), name='atualizar_post'),
    path('<int:pk>/deletar/', DeletarPost.as_view(), name='deletar_post'),
    path('categorias/', ListarCategorias.as_view(), name="listar_categorias"),
    path('categorias/<int:pk>/', VerDetalhesCategorias.as_view(), name='detalhe_categoria'),
    path('categorias/criar/', CriarCategoria.as_view(), name="criar_categoria"),
    path('categorias/<int:pk>/atualizar/', AtualizarCategoria.as_view(), name='atualizar_categoria'),
    path('categorias/<int:pk>/deletar/', DeletarCategoria.as_view(), name='deletar_categoria'),
]

techblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler400, handler403,handler404, handler500)
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from contas.views import HomepageView, CriarContaView,AjudaView
from contas.forms import MeuLoginForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomepageView.as_view(), name='homepage'),
    path('ajuda/', AjudaView.as_view(), name="ajuda"),
    path('blog/', include('postagens.urls', namespace='blog')),
    path('perfil/', include('contas.urls', namespace='perfil')),
    path('login/', LoginView.as_view(authentication_form=MeuLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', CriarContaView.as_view(), name='registro'),
    path('djrichtextfield/', include('djrichtextfield.urls'))
]

handler404 = "contas.views.pagina_nao_encontrada_view"
handler400 = "contas.views.pagina_requisicao_negadada"
handler403 = "contas.views.pagina_permissao_negada_view"
handler500 = "contas.views.pagina_error_view"
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contas/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from PIL import Image

class Usuario(AbstractUser):
    admin = models.BooleanField(default=False)
    foto = models.ImageField(upload_to="usuarios/", default="usuarios/predefinido/businessman.png")

    def save(self, *args, **kwargs):
        super().save() # salva a imagem primeiro

        img = Image.open(self.foto.path) # Abrindo imagem usando SELF

        if img.height > 500 or img.width > 500:
            nova_foto = (500,500)
            img.thumbnail(nova_foto)
            img.save(self.foto.path) # Salva nova imagem no mesmo local

contas/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import AuthenticationForm, UsernameField,UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext, gettext_lazy as _



User = get_user_model()


class MeuLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        field_classes = {'username':UsernameField}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'w-full border-2 bg-white/40  text-xl m-2 rounded-xl pl-1'})
        self.fields['password'].widget.attrs.update({'class':'w-full border-2 bg-white/40  text-xl m-2 rounded-xl pl-1'})

class CriarUsuarioCustomizadoForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'foto',
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
            
        )
        field_classes = {'username':UsernameField}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['email'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['first_name'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['last_name'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['foto'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['password1'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1 '})
        self.fields['password2'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})

class EditarUsuarioSimplesForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'foto',
            'username',
            'email',
            'first_name',
            'last_name'
        )
        field_classes = {'username':UsernameField}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['email'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['first_name'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['last_name'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})
        self.fields['foto'].widget.attrs.update({'class':'w-full border-2 bg-white/40  m-2 rounded-xl pl-1'})


class MeuSetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _('Senhas não combinam.'),
    }
    new_password1 = forms.CharField(
        label=_("Nova Senha"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'w-full text-black'}),
        strip=False,
        
    )
    new_password2 = forms.CharField(
        label=_("Confirmação de Nova Senha"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class':'w-full text-black'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

    def save(self, commit=True):
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class TrocadeSenhaForm(MeuSetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = {
        **MeuSetPasswordForm.error_messages,
        'password_incorrect': _("Sua senha antiga foi não confere, Por favor tente novamente."),
    }
    old_password = forms.CharField(
        label=_("Senha Antiga"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True , 'class':'w-full text-black'}),
    )

    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validate that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

contas/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.core.mail import send_mail

from .models import Usuario

from .forms import CriarUsuarioCustomizadoForm, EditarUsuarioSimplesForm, TrocadeSenhaForm

from postagens.models import Postagem

User = get_user_model()



class HomepageView(generic.TemplateView):
    template_name = "homepage.html"

class AjudaView(generic.TemplateView):
    template_name = "ajuda.html"

class CriarContaView(generic.CreateView):
    template_name = "registration/registro.html"
    form_class = CriarUsuarioCustomizadoForm

    def get_success_url(self):
        return reverse('login')
    
    def form_valid(self,form):
        usuario = form.save(commit = False)
        usuario.save()
        send_mail(
            subject="Conta no TechBlog Criada com Sucesso",
            message="Bem vindo, agora você faz parte do maior blog de tecnologia do mundo",
            from_email="admin@techblog_test.com",
            recipient_list=[usuario.email]
        )
        return super(CriarContaView, self).form_valid(form)

def EditarContaView(request):
    if request.user.is_authenticated:
        usuario = Usuario.objects.get(pk = request.user.pk)
        form = EditarUsuarioSimplesForm(instance = usuario)
        context ={}
        if request.method == "POST":
            form = EditarUsuarioSimplesForm(request.POST, request.FILES, instance = usuario)
            if form.is_valid():
                form.save()
                return redirect("/perfil/")
        else:
            context["usuario"] = usuario
            context["form"] = form 
            return render(request, "editar_perfil.html", context)
    else:
        return redirect("/login/")

class AtualizarSenhaContaView(LoginRequiredMixin, generic.FormView):
    template_name = "mudar_senha.html"
    form_class = TrocadeSenhaForm
    model = User

    def get_form_kwargs(self):
        kwargs = super(AtualizarSenhaContaView, self).get_form_kwargs()
        kwargs['user'] = self.request.user 
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs 

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super(AtualizarSenhaContaView, self).form_valid(form)

    def get_success_url(self):
        return reverse('meu_perfil')


    

class MeuPerfilView(LoginRequiredMixin, generic.TemplateView):
    template_name = "meu_perfil.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        postagens = Postagem.objects.filter(autor__id = self.request.user.id)
        data['ultimo_post'] = postagens.first()
        data['contagem_posts'] = postagens.count()
        return data

class MeusPostsView(LoginRequiredMixin, generic.ListView):
    template_name = "postagens/listar_postagens.html"
    context_object_name = "postagens"
    model = Postagem

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        postagens = Postagem.objects.filter(autor__id = self.request.user.id)
        data['postagens'] = postagens
        data['mensagem'] = f"do {self.request.user.username}"
        return data


def pagina_nao_encontrada_view(request, exception):
    return render(request, 'errors/404.html', exception)

def pagina_error_view(request, exception=None):
    return render(request, "errors/500.html",{})

def pagina_permissao_negada_view(request, exception=None):
    return render(request, "errors/403.html", {})

def pagina_error_csrf_view(request, reason=""):
    ctx = {'message': 'Voce não tem permissão para realizar está ação'}
    return render(request, 'errors/403_csrf.html', ctx)

def pagina_requisicao_negadada(request, exception=None):
    return render(request, "errors/400.html",{})

contas/templates/editar_perfil.html
{% extends "base.html" %} {% block content %}
<div class="xl:w-1/2 md:w-2/3 mx-auto mt-20 mb-4 flex gap-2 justify-center">
  <div
    class="bg-gray-700/60 backdrop-blur-sm rounded-xl border border-white p-4 flex flex-col"
  >
    <img src="{{usuario.foto.url}}" alt="foto perfil" class="rounded-xl" />
    <div class="text-xl pl-2 text-white">
      <div class="flex gap-1">
        <span>Username:</span>
        <h3>{{usuario.username}}</h3>
      </div>
      <div class="flex gap-1">
        <span>Desde:</span>
        <h3>{{usuario.date_joined | date:'d/m/Y'}}</h3>
      </div>
      <div class="flex gap-1">
        <span>Nome:</span>
        <h3>{{usuario.first_name}} {{usuario.last_name}}</h3>
      </div>
      <div class="flex gap-1">
        <span>Email:</span>
        <h3>{{usuario.email}}</h3>
      </div>
    </div>
  </div>
  <form
    method="POST"
    class="bg-gray-700/60 backdrop-blur-sm rounded-xl border border-white p-2"
    enctype="multipart/form-data"
  >
    <h1
      class="text-3xl font-semibold uppercase underline text-center m-2 text-white"
    >
      Editar Perfil
    </h1>
    {% csrf_token %}
    <div class="p-2 text-white text-2xl font-semibold">{{form.as_p}}</div>
    <div class="mt-2 flex gap-2 justify-center text-center">
      <button
        class="px-2 py-1 bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 rounded-xl text-xl transition ease-in-out duration-700"
      >
        Confirmar
      </button>
      <a
        href="{% url 'perfil:meu_perfil' %}"
        class="px-2 py-1 bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 rounded-xl text-xl transition ease-in-out duration-700"
        >Cancelar</a
      >
    </div>
  </form>
</div>
{% endblock content %}

contas/templates/meu_perfil.html
{% extends "base.html" %} {% block content %}
<div
  class="bg-gray-700/60 backdrop-blur-sm text-white mx-auto p-4 xl:w-2/3 md:w-4/5 mt-20 mb-4 rounded-xl border border-white"
>
  <div class="flex flex-col">
    <h1 class="text-center text-5xl mb-2 underline uppercase">Perfil</h1>
    <div
      class="flex gap-2 mx-auto justify-center bg-black/40 border border-white rounded-xl p-2"
    >
      <div class="flex flex-col text-center">
        <img
          class="rounded-xl foto_perfil"
          src="{{request.user.foto.url}}"
          alt="foto perfil"
        />
      </div>
      <div class="flex flex-col gap-2 text-left p-2 mt-4">
        <div class="flex gap-1">
          <span>Username:</span>
          <h3>{{request.user.username}}</h3>
        </div>
        <div class="flex gap-1">
          <span>Desde:</span>
          <h3>{{request.user.date_joined | date:"d/m/Y"}}</h3>
        </div>
        <div class="flex gap-1">
          <span>Nome:</span>
          <h3>{{request.user.first_name}} {{request.user.last_name}}</h3>
        </div>
        <div class="flex gap-1">
          <span>Email:</span>
          <h3>{{request.user.email}}</h3>
        </div>
        <div class="flex gap-2">
          <a
            href="{% url 'perfil:editar_perfil' %}"
            class="float-left bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 px-2 py-1"
            >Editar</a
          >
          <a
            href="{% url 'perfil:editar_senha' %}"
            class="float-left bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 px-2 py-1"
            >Editar Senha</a
          >
        </div>
      </div>
    </div>
    <div class="p-2 m-2 w-full mx-auto border border-white rounded-xl">
      <h1 class="text-center text-4xl underline uppercase">Minhas Postagens</h1>
      {% if request.user.is_authenticated %}
      <div class="flex justify-center gap-2 mt-4 font-semibold">
        <a
          href="{% url 'blog:criar_post' %}"
          class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 px-2 py-1 rounded-xl"
          >Nova Postagem</a
        ><a
          href="{% url 'perfil:minhas_postagens' %}"
          class="border border-red-600 hover:border-red-800 hover:bg-red-800 text-red-600 hover:text-gray-200 px-2 py-1 rounded-xl"
          >Ver Todas</a
        >
      </div>
      {% else %} {% endif %}

      <div class="text-center w-52 mx-auto">
        <h2 class="text-2xl mb-4 uppercase">Quantidade</h2>
        <span
          class="border-4 border-red-600 w-26 rounded-full px-6 text-6xl font-bold"
        >
          {{contagem_posts}}
        </span>
      </div>
      <div class="text-center mt-4">
        <h1 class="text-2xl uppercase mb-2">Ultima postagem</h1>
        {% comment %} Div Postagem {% endcomment %} {% if ultimo_post %}
        <div class="py-8 px-4 bg-black/40 border-2 border-white rounded-xl">
          <div class="h-full flex items-start">
            <div
              class="w-12 flex-shrink-0 flex flex-col text-center leading-none"
            >
              <span class="text-white pb-2 mb-2 border-b-2 border-gray-200"
                >{{ultimo_post.data_adicao | date:'M'}}</span
              >
              <span
                class="font-medium text-lg text-white title-font leading-none"
                >{{ultimo_post.data_adicao | date:'d'}}</span
              >
            </div>
            <div class="flex-grow pl-6">
              <h2
                class="tracking-widest text-xs title-font font-medium text-red-600 mb-1"
              >
                TÍTULO
              </h2>
              <h1 class="title-font text-xl font-medium text-white mb-3">
                {{ultimo_post.titulo}}
              </h1>
              <p class="leading-relaxed text-gray-200 mb-5">
                {{ultimo_post.texto |slice:":200"}}...
              </p>
              <div class="mb-2">
                <a
                  class="text-red-400 hover:text-red-600 font-semibold px-2 py-1 rounded-md"
                  href="{% url 'blog:detalhe_post' ultimo_post.pk %}"
                  >Ler Mais</a
                >
              </div>
              <div class="mb-2 border border-white"></div>
              <a class="inline-flex items-center">
                <span
                  class="text-2xl font-bold bg-red-600 text-white px-3 py-1 rounded-full"
                  >A</span
                >
                <span class="flex-grow flex flex-col pl-2">
                  <span class="title-font font-medium text-white"
                    >{{ultimo_post.autor}}</span
                  >
                </span>
              </a>
            </div>
          </div>
        </div>
        {% else %}
        <div class="py-8 px-4 bg-black/40 border-2 border-white rounded-xl">
          <h1 class="text-5xl">Sem Postagens</h1>
        </div>
        {% endif %} {% comment %} Div Postagem {% endcomment %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

contas/templates/mudar_senha.html
{% extends "base.html" %} {% block content %}
<div class="flex items-center posicionar_items">
  <div
    class="bg-gray-700/60 backdrop-blur-sm text-white p-4 md:w-1/2 xl:w-1/3 mx-auto rounded-xl border-2 border-white"
  >
    <h1
      class="text-3xl font-bold uppercase p-2 text-center border-b-2 border-white"
    >
      Alterar Senha
    </h1>
    <form method="POST" class="text-xl font-semibold">
      {% csrf_token %} {{form.as_p}}
      <div class="text-gray-300 text-base text-left">
        <p>Não use senha com informações pessoais.</p>
        <p>Sua senha precisa ter no mínimo 8 caracteres.</p>
        <p>Sua senha não pode ser uma senha muito comum ex: 12345678</p>
        <p>Sua senha não pode ser completamente numérica.</p>
      </div>
      <div class="flex gap-2 justify-center mt-2">
        <button
          class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 px-2 py-1 text-xl rounded-xl transition ease-in-out duration-700"
        >
          Confirmar
        </button>
        <a
          class="bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 px-2 py-1 text-xl rounded-xl transition ease-in-out duration-700"
          href="{% url 'perfil:meu_perfil' %}"
          >Cancelar</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock content %}