contas/urls.py
from django.urls import path

from .views import MeuPerfilView, EditarContaView, AtualizarSenhaContaView, MeusPostsView


app_name = "perfil"

urlpatterns = [
    path('',MeuPerfilView.as_view(), name='meu_perfil'),
    path('editar/', EditarContaView, name='editar_perfil'),
    path('editar_senha/', AtualizarSenhaContaView.as_view(), name="editar_senha"),
    path('posts/', MeusPostsView.as_view(), name='minhas_postagens'),
]

postagens/urls.py
from django.urls import path

from .views import (
    ListarPosts,
    VerDetalhesPosts,
    ListarPostsPorCategoria,
    CriarPost,
    AtualizarPost,
    DeletarPost,
    ListarCategorias,
    VerDetalhesCategorias,
    CriarCategoria,
    AtualizarCategoria,
    DeletarCategoria
)

app_name = "blog"

urlpatterns = [
    path('', ListarPosts.as_view(), name="listar_posts"),
    path('<int:pk>/', VerDetalhesPosts.as_view(), name='detalhe_post'),
    path('por_categoria/<titulo>/', ListarPostsPorCategoria.as_view(), name='listar_posts_por_categoria'),
    path('criar/', CriarPost.as_view(), name="criar_post"),
    path('<int:pk>/atualizar/', AtualizarPost.as_view(), name='atualizar_post'),
    path('<int:pk>/deletar/', DeletarPost.as_view(), name='deletar_post'),
    path('categorias/', ListarCategorias.as_view(), name="listar_categorias"),
    path('categorias/<int:pk>/', VerDetalhesCategorias.as_view(), name='detalhe_categoria'),
    path('categorias/criar/', CriarCategoria.as_view(), name="criar_categoria"),
    path('categorias/<int:pk>/atualizar/', AtualizarCategoria.as_view(), name='atualizar_categoria'),
    path('categorias/<int:pk>/deletar/', DeletarCategoria.as_view(), name='deletar_categoria'),
]

techblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (handler400, handler403,handler404, handler500)
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from contas.views import HomepageView, CriarContaView,AjudaView
from contas.forms import MeuLoginForm



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomepageView.as_view(), name='homepage'),
    path('ajuda/', AjudaView.as_view(), name="ajuda"),
    path('blog/', include('postagens.urls', namespace='blog')),
    path('perfil/', include('contas.urls', namespace='perfil')),
    path('login/', LoginView.as_view(authentication_form=MeuLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registro/', CriarContaView.as_view(), name='registro'),
    path('djrichtextfield/', include('djrichtextfield.urls'))
]

handler404 = "contas.views.pagina_nao_encontrada_view"
handler400 = "contas.views.pagina_requisicao_negadada"
handler403 = "contas.views.pagina_permissao_negada_view"
handler500 = "contas.views.pagina_error_view"
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/ajuda.html
{% extends "base.html" %} {% block content %}
<div class="flex items-center posicionar_items w-2/3 mx-auto">
  <div
    class="bg-gray-700/60 mx-auto backdrop-blur-sm p-8 m-2 rounded-3xl border border-white"
  >
    <h1 class="text-white text-5xl underline uppercase text-center mb-2">
      Ajuda
    </h1>
    <div class="text-white text-xl">
      <div class="ml-4">
        <li>Crie uma conta caso queira criar seus proprios posts</li>
        <li>
          Para editar seus proprios posts, navegue até o seu perfil e clique em
          "ver todas", apos isso escolha um post, clique em ler mais e depois em
          editar
        </li>
        <li>
          Se seu post abrange sobre algum assunto que não contenha a categoria
          registrada no nosso blog entre em contato com o administrador via
          e-mail - admin@mail.com
        </li>
      </div>
      <h1 class="text-white text-5xl underline uppercase text-center mb-2">
        REGRAS
      </h1>
      <div class="ml-4">
        <li>
          Os posts deverão ter como tema tecnologia ex: Reactjs, Javascript,
          Celulares, Computadores e etc...
        </li>
        <li>
          É completamente proibido conteudo ofensivo ex: postagens racistas,
          homofobicas ou qualquer discurso de ódio
        </li>
        <li>Proibido spam(repetição) do mesmo conteudo</li>
      </div>
      <div class="mt-2 flex gap-2 justify-center">
        <a
          href="{% url 'homepage' %}"
          class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 px-2 py-1 text-2xl rounded-xl"
          >Voltar a Pagina Principal</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{%  static 'images/projeto/techlogo.svg' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>TechBlog</title>
    <script src="https://cdn.tailwindcss.com"></script>
    {{ form.media }}
  </head>
  <body class="h_adjust">
    {% include 'navbar.html' %}
    <div>{% block content %} {% endblock content %}</div>
    {% include "scripts.html" %}
  </body>
</html>

templates/homepage.html
{% extends "base.html" %}{% load static %} {% block content %}
<div class="flex items-center posicionar_items">
  <div class="w-2/3 mx-auto">
    {% if message %}
    <h1
      class="text-center p-2 border border-white rounded-3xl text-xl uppercase text-red-600 font-bold bg-black mb-2"
    >
      {{message}}
    </h1>
    {% else %} {% endif %}

    <div
      class="flex gap-10 justify-center bg-gray-700/60 backdrop-blur-sm p-8 rounded-3xl border border-white"
    >
      <div class="xl:w-2/5 md:w-full self-center">
        <h1
          class="xl:text-6xl md:text-3xl text-white text-justify p-2 font-semibold"
        >
          <span class="font-bold text-red-600 text-7xl">T</span>ECH BLOG
        </h1>
        <h2 class="xl:text-xl md:text-md text-left p-2 pl-4 text-gray-200">
          Esse blog é dedicado a ajudar você a ficar antenado as últimas
          tecnologias do mercado. Sobre lançamento de novos frameworks,
          linguagens de programação ou outras tecnologias, sacie agora sua
          curiosidade.
        </h2>
        <div class="flex p-2">
          <a
            href="{% url 'blog:listar_posts' %}"
            class="bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 p-2 ml-2 text-xl font-semibold transition ease-in-out duration-700"
          >
            Postagens
          </a>
        </div>
      </div>
      <img
        src="{%  static 'images/projeto/blog-writing.svg' %}"
        alt="hero_image"
        class="rounded-full p-2 w-1/2 xl:block md:hidden"
      />
    </div>
  </div>
</div>
{% endblock content %}

templates/navbar.html
{% load static %}
<header class="body-font bg-gray-700/60 backdrop-blur-sm">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <nav
      class="flex lg:w-2/5 flex-wrap items-center text-white text-md font-semibold md:ml-auto"
    >
      <a
        href="{% url 'homepage' %}"
        class="hover:text-red-600 mr-5 transition ease-in-out duration-700 p-1 rounded-xl"
        >Home</a
      >
      <a
        href="{% url 'blog:listar_posts'%}"
        class="hover:text-red-600 mr-5 transition ease-in-out duration-700 p-1 rounded-xl"
        >Postagens</a
      >
      <a
        href="{% url 'blog:listar_categorias' %}"
        class="hover:text-red-600 mr-5 transition ease-in-out duration-700 p-1 rounded-xl"
        >Categorias</a
      >
      <a
        href="{% url 'ajuda' %}"
        class="hover:text-red-600 mr-5 transition ease-in-out duration-700 p-1 rounded-xl"
        >Ajuda</a
      >
    </nav>
    <a
      href="{% url 'homepage' %}"
      class="flex order-first lg:order-none lg:w-1/5 title-font font-medium items-center text-red-600 lg:items-center lg:justify-center mb-4 md:mb-0"
    >
      <img
        class="w-16 p-0 hover:animate-pulse"
        src="{% static 'images/projeto/techlogo.svg' %}"
        alt=""
      />
    </a>
    <div class="lg:w-2/5 inline-flex lg:justify-end ml-5 lg:ml-0 flex gap-2">
      {% if request.user.is_authenticated %}
      <a
        href="{% url 'perfil:meu_perfil' %}"
        class="inline-flex items-center border border-red-600 hover:border-red-800 hover:bg-red-800 text-red-600 hover:text-gray-200 font-semibold py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0 shadow-md transition ease-in-out duration-700"
        >Perfil</a
      >
      <a
        href="{% url 'logout' %}"
        class="inline-flex items-center bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 font-semibold border-0 py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0 shadow-md transition ease-in-out duration-700"
      >
        Logout
      </a>

      {% else %}
      <a
        href="{% url 'registro' %}"
        class="inline-flex items-center bg-blue-600 hover:bg-blue-800 text-white hover:text-gray-200 font-semibold border-0 py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0 shadow-md transition ease-in-out duration-700"
      >
        Registro
      </a>
      <a
        href="{% url 'login' %}"
        class="inline-flex items-center bg-red-600 hover:bg-red-800 text-white hover:text-gray-200 font-semibold border-0 py-1 px-3 focus:outline-none rounded text-base mt-4 md:mt-0 shadow-md transition ease-in-out duration-700"
      >
        Login
      </a>
      {% endif %}
    </div>
  </div>
</header>